add authorization app
textify-bundle/textify-frontend pull request #12
Opened 2024-11-09 17:21 UTC by poplopok

add authorization: store, services, client supabase

2024-11-11 20:39 UTC, bassceo commented
@@CodiumAI-Agent /review

2024-11-11 20:39 UTC, bassceo commented
@CodiumAI-Agent /review

2024-11-11 20:41 UTC, bassceo commented
@coderabbitai summary

2024-11-11 20:44 UTC, bassceo commented
@coderabbitai full review

2024-11-11 20:54 UTC, bassceo commented
Все коментарии выше актуальны +
1) В shared/api не должно быть никаких файлов tsx, scss, css, кроме ts

2024-11-12 12:33 UTC, bassceo commented
@coderabbitai review

2024-11-12 16:48 UTC, ValeriyaKa commented on src/widgets/index.scss
> +  min-height: 260px; /* Минимальная высота для блока с формой */
убрать все русские коментарии

2024-11-12 19:42 UTC, bassceo requested changes

2024-11-12 19:42 UTC, bassceo commented on src/features/Auth/AuthService.ts
> +    },
давай унесем это в api  пожалуйста

2024-11-12 19:42 UTC, bassceo commented on src/main.tsx
> +  );
мб без чатгпт комментов?

2024-11-12 19:42 UTC, bassceo commented on src/pages/LoginPgae/LoginPage.tsx
> +            Зарегистрироваться
Login и Registration могут быть вполне одним компонетном, не очень понятно почему-то ты такой большой монолитный кусок кода оставил, разбей на компоненты

2024-11-17 18:37 UTC, closed without merging

2024-11-17 18:38 UTC, bassceo commented
смерджил